version: '3'

services:
  ## django
  djangoapp:
    # location of the django dockerfile
    build: ./django
    ports:
      - "5000:5000"
    command: gunicorn djangoapp.wsgi:application --bind 0.0.0.0:5000
    # command: python manage.py runserver 0.0.0.0:5000
    volumes:
      # The below mapping ensures that changes at ./django/djangoapp of host get
      # reflected in realtime at /djangoapp of the container
      - ./django/djangoapp:/djangoapp
      # - static_volume:/djangoapp/staticfiles
      # - media_volume:/djangoapp/media
    networks:
      - network_web
  ## nginx
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - djangoapp
    networks:
      - network_web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./django/djangoapp/staticfiles:/djangoapp/staticfiles
      - ./django/djangoapp/media:/djangoapp/media

networks:
  network_web:
    driver: bridge
# volumes:
#   static_volume:
#   media_volume:
